In [58]:
import torch

# Compute gradient of $y=2x^{T}x$

In [114]:
x = torch.arange(4.0)
x.requires_grad_(True)
y = 2 * torch.dot(x, x)
y.backward()
x.grad == 4 * x

tensor([True, True, True, True])

# Compute gradiet of some other function of $x$

In [115]:
x.grad.zero_() # Very crucial, if not set to zero it will add the current value to the value in buffer
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [88]:
y.grad_fn

In [55]:
z = x * x
z.sum().backward()
x.grad

tensor([ 0.,  6., 12., 18.])

In [56]:
# gradient of a function
def func(x):
    return x * x * x

In [57]:
x

tensor([0., 1., 2., 3.], requires_grad=True)